FROM node:18 as build-stage

WORKDIR /app

COPY ./vue/package*.json ./

RUN npm install

COPY ./vue .

RUN npm run build

FROM nginx:1.21 as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]