version: '3'
services:
  iwhata:
    build: 
      context: .
      dockerfile: Dockerfile-ubuntu
    image: iwhata
    volumes:
      - .:/iwhata
    working_dir: /iwhata
    ports:
      - "1317:1317"
      - "4500:4500"
      - "26657:26657"
    command: ignite chain serve
    networks:
      - iwhataNetwork
  # vueapp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-webapp
  #   ports:
  #     - "80:80"
  #   networks:
  #     - iwhataNetwork
  vueapp:
    image: node:18
    volumes:
      - ./vue:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: bash -c "npm install && npm run dev -- --host"
    networks:
      - iwhataNetwork

networks:
  iwhataNetwork: